const AppImage = {
    background: require('~assets/img/img_background.png'),
    logo: require('~assets/img/img_logo.png'),
    flag: require('~assets/img/img_flag.png'),
    avatar: require('~assets/img/img_avatar.png'),
    imgQuestion: require('~assets/img/img_question.png'),
    imgComment: require('~assets/img/img_comment.png'),
    expertAvatar: require('~assets/img/img_expert_avatar.png'),
    imgNews: require('~assets/img/img_news.png'),
    userIcon: require('~assets/img/icon_user.png'),
    passwordIcon: require('~assets/img/icon_lock.png'),
    hidePasswordIcon: require('~assets/img/icon_hide_password.png'),
    showPasswordIcon: require('~assets/img/icon_show_password.png'),
    downArrowIcon: require('~assets/img/icon_down_arrow.png'),
    leftArrowIcon: require('~assets/img/icon_left_arrow.png'),
    phoneIcon: require('~assets/img/icon_phone.png'),
    checkIcon: require('~assets/img/icon_check.png'),
    homeIcon: require('~assets/img/icon_home.png'),
    communityIcon: require('~assets/img/icon_community.png'),
    newIcon: require('~assets/img/icon_new.png'),
    mapIcon: require('~assets/img/icon_map.png'),
    focusHomeIcon: require('~assets/img/icon_home_focus.png'),
    focusCommunityIcon: require('~assets/img/icon_community_focus.png'),
    focusNewIcon: require('~assets/img/icon_new_focus.png'),
    searchIcon: require('~assets/img/icon_search.png'),
    notificationIcon: require('~assets/img/icon_notification.png'),
    sendIcon: require('~assets/img/icon_send.png'),
    heartIcon: require('~assets/img/icon_heart.png'),
    commentIcon: require('~assets/img/icon_comment.png'),
    shareIcon: require('~assets/img/icon_share.png'),
    notificationIcon: require('~assets/img/icon_notification.png'),
    avata:require('~assets/img/img_avata.png'),
    gold_Medal: require('~assets/img/img_gold_medal.png'),
    silver_Medal: require('~assets/img/img_silver_medal.png'),
    bronze_Medal: require('~assets/img/img_bronze_medal.png'),
    share:require('~assets/img/img_share.png'),
    posterEvent:require('~assets/img/img_poster_event.png'),
    date:require('~assets/img/icon_calendar.png'),
    posterNews:require('~assets/img/img_poster_news.png'),
    posterLocation:require('~assets/img/img_poster_location.png'),
    MapTest:require('~assets/img/img_MapTest.png'),
    LocationIconMy:require('~assets/img/icon_locationMy.png'),
    PosterNewsHome:require('~assets/img/img_news_poster_home.png'),
}

export default AppImage;